claror_feina_homepage:
    pattern:  /demo/post
    defaults: { _controller: ClarorFeinaBundle:Default:posts }

Anota:
    resource: "@ClarorFeinaBundle/Controller/"
    prefix:   /
    type:     annotation
    requirements:
        _locale: ca|es
    prefix: /{_locale}/        
