home_gestor:
    pattern:  /{_locale}/gestor
    defaults: { _controller: ClarorFeinaBundle:Fijas:index }
    prefix:   /
    requirements:
        _locale: ca|es
    
Anota:
    resource: "@ClarorFeinaBundle/Controller/"
    prefix:   /
    type:     annotation
    requirements:
        _locale: ca|es
    prefix: /{_locale}/        
