parameters:
#    claror_feina.example.class: Claror\FeinaBundle\Example

services:
#    claror_feina.example:
#        class: %claror_feina.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]

    vabadus.form.type.entity_id:
        class: Claror\FeinaBundle\Form\Type\EntityIdType
        arguments: [@doctrine.orm.entity_manager]
        tags:
            - { name: form.type, alias: entity_id }
