<?php

namespace Claror\FeinaBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CategoriaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoriaRepository extends EntityRepository
{
	
    public function getNasociados()
    {
        return $this->getEntityManager()
                ->createQuery('SELECT COUNT(f.id) FROM ClarorFeinaBundle:Faena WHERE f.categoria >0')
                ->getResults;
    }
	
}
