<?php

namespace Claror\FeinaBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * FaenaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FaenaRepository extends EntityRepository
{
}
