<?php

namespace Claror\FeinaBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * FaenaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FaenaRepository extends EntityRepository
{
	
    public function findByTieneCategoria($id)
    {
        return $this->getEntityManager()
                ->createQuery('SELECT COUNT(f.id) as total FROM ClarorFeinaBundle:Faena f WHERE f.categoria=:idcat ')->setParameter('idcat',$id);
    }	


    public function findByTieneFabricante($id)
    {
        return $this->getEntityManager()
                ->createQuery('SELECT COUNT(f.id) as total FROM ClarorFeinaBundle:Faena f WHERE f.fabricante=:idcat ')->setParameter('idcat',$id);
    }

}
