parameters:
#    claror_idioma.example.class: Claror\IdiomaBundle\Example

services:
#    claror_idioma.example:
#        class: %claror_idioma.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
