gestor_sitemap:
    resource: "@GestorSitemapBundle/Resources/config/routing.yml"
    prefix:   /

gestor_crud:
    resource: "@GestorCrudBundle/Resources/config/routing.yml"
    prefix:   /

gestor_menu:
    resource: "@GestorMenuBundle/Resources/config/routing.yml"
    prefix:   /

claror_idioma:
    resource: "@GestorIdiomaBundle/Resources/config/routing.yml"
    prefix:   /

claror_security:
    resource: "@GestorSecurityBundle/Resources/config/routing.yml"
    prefix:   /


login:
    pattern:   /gestor/login
    defaults:  { _controller: GestorSecurityBundle:Security:login }
login_check:
    pattern:   /gestor/login_check

logout:
    path:   /gestor/logout
