claror_idioma:
    resource: "@GestorIdiomaBundle/Resources/config/routing.yml"
    prefix:   /

claror_security:
    resource: "@GestorSecurityBundle/Resources/config/routing.yml"
    prefix:   /

claror_feina:
    resource: "@GestorFeinaBundle/Resources/config/routing.yml"
    prefix:   /

login:
    pattern:   /gestor/login
    defaults:  { _controller: GestorSecurityBundle:Security:login }
login_check:
    pattern:   /gestor/login_check

logout:
    path:   /gestor/logout
