security:
    role_hierarchy:
        ROLE_USUARIO:    IS_AUTHENTICATED_ANONYMOUSLY
        ROLE_ADMIN:       ROLE_USUARIO
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, IS_AUTHENTICATED_ANONYMOUSLY ,ROLE_ALLOWED_TO_SWITCH]
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext        
    encoders:
        Symfony\Component\Security\Core\User\User: 
            algorithm:  sha1
            iterations: 1
            encode_as_base64: false
            

    providers:
        default_provider:
            memory:
                users:
                    a: { password:86f7e437faa5a7fce15d1ddcb9eaeaea377667b8, roles: 'ROLE_SUPER_ADMIN'}    

    firewalls:
        secured_area:
            pattern:    /gestor/*
            anonymous: ~
            form_login:
                login_path:  login
                check_path:  login_check
            logout:
                path: /gestor/logout
                target: /gestor/login

    access_control:
      - { path: /gestor/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
      - { path: /gestor, roles: [ROLE_USUARIO,ROLE_VISITA] }

