security:
    role_hierarchy:
        ROLE_USUARIO:    IS_AUTHENTICATED_ANONYMOUSLY
        ROLE_ADMIN:       ROLE_USUARIO
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, IS_AUTHENTICATED_ANONYMOUSLY ,ROLE_ALLOWED_TO_SWITCH]
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext        
    encoders:
        Symfony\Component\Security\Core\User\User: 
            algorithm:  sha1
            iterations: 1
            encode_as_base64: false
            

    providers:
        default_provider:
            memory:
                users:
                    raspinu: { password:0cab848c82426d8cd47736c8fb42f1403047a661, roles: 'ROLE_SUPER_ADMIN'}  
                    trepax: { password:aa15d5b0317368871c42acaa4e4ed2935ed5041c, roles: 'ROLE_ADMIN'}
                    adminclaror: { password:6dd7cd79b06cdbe86a910ca021f9ec0c6d439914, roles: 'ROLE_ADMIN'}   

    firewalls:
        secured_area:
            pattern:    /gestor/*
            anonymous: ~
            form_login:
                login_path:  login
                check_path:  login_check
            logout:
                path: /gestor/logout
                target: /gestor/login

    access_control:
      - { path: /gestor/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
      - { path: /gestor, roles: [ROLE_USUARIO,ROLE_VISITA] }

