<?php

namespace Claror\FeinesBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * FeinaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FeinaRepository extends TranslatableRepository
{
}
