parameters:
#    gestor_sitemap.example.class: Gestor\SitemapBundle\Example

services:
#    gestor_sitemap.example:
#        class: %gestor_sitemap.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
