parameters:
#    claror_security.example.class: Claror\SecurityBundle\Example

services:
#    claror_security.example:
#        class: %claror_security.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
