parameters:
    MiemLis: Noticia*titulo*creacion/fecha*texto/corta-2*autor|Categoria*nombre*descripcion/corta-10
    EntidadesConImg: noticia
    
    
# parametros para idiomas
    idiomas_crud: ca,es
    
# parametros para sitemap
    elsitemap: Noticia*locale/#fija-a#/titulo/id|Categoria*locale/nombre/id   
    
# Namespace Entidad base y Type 
    rutaEN: Gestor\CrudBundle\Entity\
    nameEN: GestorCrudBundle:
    rutaTY: Gestor\CrudBundle\Form\   
