gestor_crud_homepage:
    pattern:  /{_locale}/home
    defaults: { _controller: GestorCrudBundle:Fijas:index }
    requirements:
        _locale: ca|es
    prefix: /{_locale}/ 


gestor_listar_orden_col:
    pattern:  /{_locale}/listar/{pagina}/{orden}/{campo}/{entidad}
    defaults: { _controller: GestorCrudBundle:Lista:listar  }
    requirements:
        _locale: ca|es
        pagina:  \d+ 
        orden: ASC|DESC
    prefix: /{_locale}/ 
 


gestor_editar_nuevo:
    pattern:  /{_locale}/nuevo/{entidad}
    defaults: { _controller: GestorCrudBundle:Editar:nuevo  }
    requirements:
        _locale: ca|es
    prefix: /{_locale}/     
 


gestor_editar_registro:
    pattern:  /{_locale}/editar/{id}/{entidad}
    defaults: { _controller: GestorCrudBundle:Editar:editar  }
    requirements:
        _locale: ca|es
    prefix: /{_locale}/  

gestor_actualizar_registro:
    pattern:  /{_locale}/actualizar/{id}/{entidad}
    defaults: { _controller: GestorCrudBundle:Editar:actualizar  }
    requirements:
        _locale: ca|es
    prefix: /{_locale}/  


gestor_eliminar_1_registro:
    pattern:  /{_locale}/eliminar/{id}/{ok}/{entidad}
    defaults: { _controller: GestorCrudBundle:Editar:eliminar  }
    requirements:
        _locale: ca|es
    prefix: /{_locale}/  


gestor_editar_crear:
    pattern:  /{_locale}/crear/{entidad}
    defaults: { _controller: GestorCrudBundle:Editar:crear  }
    requirements:
        _locale: ca|es
    prefix: /{_locale}/ 


