gestor_crud_homepage:
    pattern:  /{_locale}/home
    defaults: { _controller: GestorCrudBundle:Fijas:index }
    requirements:
        _locale: ca|es
    prefix: /{_locale}/ 

gestor_listar_orden_col:
    pattern:  /{_locale}/listar/{pagina}/{orden}/{campo}/{entidad}
    defaults: { _controller: GestorCrudBundle:Crud:listar  }
    requirements:
        _locale: ca|es
        pagina:  \d+ 
        orden: ASC|DESC
    prefix: /{_locale}/ 
    
