parameters:
#    gestor_crud.example.class: Gestor\CrudBundle\Example

services:
#    gestor_crud.example:
#        class: %gestor_crud.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
