parameters:
    gestor_crud.paginacion: Gestor\CrudBundle\Paginacion\Paginacion

services:
    pagi:
        class: %gestor_crud.paginacion%
        
#    gestor_crud.example:
#        class: %gestor_crud.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
