gestor_menu_salida:
    pattern:  /{_locale}/menu-salida
    defaults: { _controller: GestorMenuBundle:Menu:index }

gestor_listar:
    pattern:  /{_locale}/listar/{pagina}/{entidad}
    defaults: { _controller: GestorCrudBundle:Crud:listar }
    requirements:
        pagina:  \d+
